name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I do X, Y happens instead of Z...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `ccutils sync-permissions ...`
        2. Press arrow key to navigate
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Terminal output
      description: If applicable, add screenshots or paste terminal output.
      render: shell

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "e.g., macOS 14.0, Ubuntu 22.04, Windows 11"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: "e.g., 20.10.0 (run `node -v`)"
    validations:
      required: true

  - type: input
    id: terminal
    attributes:
      label: Terminal
      placeholder: "e.g., iTerm2, Windows Terminal, Alacritty"

  - type: input
    id: ccutils-version
    attributes:
      label: ccutils version
      placeholder: "e.g., 0.1.0 (check package.json or npm)"

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
