name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: why
    attributes:
      label: Problem or motivation
      description: What problem does this feature solve? Is this related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: how
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
      placeholder: It would be great if ccutils could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: scope
    attributes:
      label: Which area does this affect?
      options:
        - TUI / User interface
        - Permission management
        - Configuration loading/saving
        - CLI arguments / commands
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, mockups, or screenshots about the feature request.
